name: task_man_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5


dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.2
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.0
  cupertino_icons: ^1.0.8
  flutter_timezone: ^3.0.1
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/app_logo.png"
  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: "assets/images/app_logo.png"

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/images/app_logo.png

